# Generated by Django 4.2.6 on 2024-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abaute_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('decspritions_1', models.TextField(blank=True)),
                ('decspritions_2', models.TextField(blank=True)),
                ('decspritions_4', models.TextField(blank=True)),
            ],
        ),
    ]
