# Generated by Django 4.2.6 on 2024-02-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abaute_us',
            name='decspritions_3',
            field=models.TextField(blank=True),
        ),
    ]
