# Generated by Django 4.2.6 on 2024-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboute', '0002_abaute_us_decspritions_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abaute_us',
            name='name',
        ),
        migrations.AddField(
            model_name='abaute_us',
            name='name_descripton',
            field=models.TextField(blank=True),
        ),
    ]
