# Generated by Django 4.2.6 on 2024-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboute', '0003_remove_abaute_us_name_abaute_us_name_descripton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abaute_us',
            name='name_descripton',
        ),
        migrations.AddField(
            model_name='abaute_us',
            name='name',
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
