# Generated by Django 4.2.6 on 2024-02-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('narx', models.IntegerField()),
                ('descpritions_1', models.TextField()),
                ('descpritions_2', models.TextField()),
                ('descpritions_3', models.TextField()),
                ('descpritions_4', models.TextField()),
                ('descpritions_5', models.TextField()),
            ],
        ),
    ]
