# Generated by Django 4.2.6 on 2024-02-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='descpritions_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='descpritions_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='descpritions_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='descpritions_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='descpritions_5',
            field=models.TextField(blank=True),
        ),
    ]
