# Generated by Django 5.0 on 2024-01-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=199)),
                ('descpritions', models.TextField()),
                ('xozirgi_narx', models.IntegerField()),
                ('oldingi_narx', models.IntegerField()),
                ('created_one', models.DateTimeField(auto_now_add=True)),
                ('categpory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category_portfolia')),
            ],
        ),
    ]
