# Generated by Django 5.0 on 2024-01-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolia',
            name='descpritions',
            field=models.TextField(blank=True),
        ),
    ]
