# Generated by Django 4.2.6 on 2024-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolia', '0002_alter_portfolia_descpritions'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolia',
            name='slug',
            field=models.SlugField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
