# Generated by Django 4.2.6 on 2024-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolia', '0003_portfolia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolia',
            name='mavjudmi',
            field=models.BooleanField(default=True),
        ),
    ]
